export default Object.freeze({
  MONTH__SET_MONTH: 'MONTH__SET_MONTH',
  MONTH__ADD_MONTH: 'MONTH__ADD_MONTH',
  MONTH__SUB_MONTH: 'MONTH__SUB_MONTH',
  MONTH__EVENTS: 'MONTH__EVENTS',
  MONTH__OPEN_MODAL: 'MONTH__OPEN_MODAL',
  MONTH__CLOSE_MODAL: 'MOTH__CLOSE_MODAL',
});
